export default [
    "Allergy",
    "Hay Fever",
    "Eczema",
    "Wheezing",
    "Shortness of Breath",
    "Breathing Difficulty",
    "Anemia",
    "High Blood Pressure",
    "Arteriosclerosis",
    "Palpitations",
    "Panic Attacks",
    "Poor Circulation",
    "Varicose Veins",
    "Hemorrhoids",
    "Hives",
    "Skin Rashes",
    "Burn",
    "Healing Wounds",
    "Bruises",
    "Cold Sores",
    "Shingles",
    "Chicken Pox",
    "Warts",
    "Athlete's Foot",
    "Acne",
    "Boils",
    "Nausea",
    "Vomitting",
    "Gas",
    "Bloating",
    "Mouth Ulcers",
    "Constipation",
    "Diarrhea",
    "Acidity",
    "Indigestion",
    "Anxiety",
    "Depression",
    "Tension",
    "Head Pain",
    "Toothache",
    "Headache",
    "Sinus Headache",
    "Migraine",
    "Hangover",
    "Insomnia",
    "Cough",
    "Sore and Tired Eyes",
    "Conjunctivitis",
    "Nosebleeds",
    "Colds",
    "Fever (high)",
    "Fever (Mild)",
    "Sore Throat",
    "Tonsillitis",
    "Earache",
    "Sprains",
    "Fractures",
    "Tired and Aching Muscles",
    "Cramps",
    "Muscle Spasms",
    "Arthritis",
    "Inflamed Joints",
    "Gout",
    "Back Pain",
    "Athlete's Foot",
    "Urinary Infections",
    "Fungal Infecton",
    "Yeast Infection",
    "Oral Thrush",
    "Candidiasis",
    "Digestive Upsets",
    "Gas",
    "Colic",
    "Diaper Rash",
    "Inflamed Skin Rashes",
    "Cradle Cap",
    "Teething",
    "Irregular Cycle",
    "Fluid Retention",
    "Breast Tenderness",
    "Heavy Menstrual Bleeding",
    "Period Pain",
    "Aiding Conception",
    "Low Sex Drive",
    "Failing Memory",
    "Concentration",
    "Poor Circulation",
    "High Blood Pressure",
    "Chronic Infections",
    "Weakened Liver",
    "Metabolism",
    "Weakened Digestion",
]