export default [
    'Allergy',
    'Eczema',
    'Anemia',
    'High Blood Pressure',
    'Arteriosclerosis',
    'Palpitations',
    'Poor Circulation',
    'Varicose Veins',
    'Hemorrhoids',
    'Hives',
    'Skin Rashes',
    'Burn',
    'Healing Wounds',
    'Bruises',
    'Cold Sores',
    'Shingles',
    'Chicken Pox',
    'Warts',
    'Athlete\'s Foot',
    'Acne',
    'Boils',
    'Nausea',
    'Vomitting',
    'Gas',
    'Bloating',
    'Mouth Ulcers',
    'Constipation',
    'Diarrhea',
    'Acidity',
    'Indigestion'
]